version: '3.8'
services:
  db:
    image: postgres:15.2-alpine
    container_name: demo-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5455:5432'
    volumes: 
      - db:/data
volumes:
  db:
    driver: local